build:
	gcc Main.c Vec.c Vec_2f.c Game.c Scene.c Texture.c Entity.c Label.c FPS_Counter.c Button.c Point.c Animation.c Sprite.c Text_Form.c Connection.c -fms-extensions -Wall -Wextra -g3 -lm -lSDL2 -lSDL2_ttf -lSDL2_image -lSDL2_net
	./a.out
