build:
	gcc Main.c String.c Array.c Game.c Scene.c Entity.c Load.c Button.c Texture.c Sprite.c Memory.c -o Program -g3 -std=c11 -fms-extensions -Wall -Wextra -lSDL2 -lSDL2_image -lSDL2_ttf
	./Program
